databases:
- engine: PG
  name: db
  num_nodes: 1
  size: db-s-dev-database
  version: "12"
envs:
- key: DISABLE_COLLECTSTATIC
  scope: RUN_AND_BUILD_TIME
  value: "1"
- key: DEBUG
  scope: RUN_AND_BUILD_TIME
  value: "0"
- key: DJANGO_ALLOWED_HOST
  scope: RUN_AND_BUILD_TIME
  value: .ondigitalocean.app
- key: DJANGO_SUPERUSER_EMAIL
  scope: RUN_AND_BUILD_TIME
  value: hello@teamcfe.com
- key: DJANGO_SUPERUSER_USERNAME
  scope: RUN_AND_BUILD_TIME
  value: cfe
- key: DJANGO_SECRET_KEY
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: is*s-5(zr#0xut8ib2!x=w&jyg78gs0u209cjfjdf)-(ds)$#3
- key: DJANGO_SUPERUSER_PASSWORD
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: )och&cu#p0ee4!q7ec_5@9=w-i61y=kzahf*h4l$+1!*rk-j6_
- key: POSTGRES_DB
  scope: RUN_AND_BUILD_TIME
  value: ${db.DATABASE}
- key: POSTGRES_HOST
  scope: RUN_AND_BUILD_TIME
  value: ${db.HOSTNAME}
- key: POSTGRES_USER
  scope: RUN_AND_BUILD_TIME
  value: ${db.USERNAME}
- key: POSTGRES_PASSWORD
  scope: RUN_AND_BUILD_TIME
  value: ${db.PASSWORD}
- key: POSTGRES_PORT
  scope: RUN_AND_BUILD_TIME
  value: ${db.PORT}
- key: AWS_ACCESS_KEY_ID
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: p-!oc($7qnt9l+@3gvn^%*q2h-!4!a@4!b!i9i#1wo)@t7^)84
- key: AWS_SECRET_ACCESS_KEY
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: 8c%2ne#ybwgh%e6kxav0l=qy+$5q77r69=%w0460c&f^((&us4
- key: AWS_STORAGE_BUCKET_NAME
  scope: RUN_AND_BUILD_TIME
  value: trydjango32
- key: OCR_API_TOKEN_HEADER
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: 9j)x*!k^w^0@6r#t@2pqxp)07-y-j5x-+1^l@p)#t)!w9jfw&@
- key: OCR_API_ENDPOINT
  scope: RUN_AND_BUILD_TIME
  value: https://fastapi-microservice-for-django-d3kjd.ondigitalocean.app
jobs:
- environment_slug: python
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${db.DATABASE_URL}
  github:
    branch: production-3
    deploy_on_push: true
    reop: olijwood/django-delights
  instance_count: 1
  instance_size_slug: basic-xxs
  kind: PRE_DEPLOY
  name: django-migrate-job
  run_command: python manage.py migrate --noinput
  source_dir: /
name: try-django-3-2
region: nyc
services:
- environment_slug: python
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${db.DATABASE_URL}
  github:
    branch: production-3
    deploy_on_push: true
    reop: olijwood/django-delights
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: djangodelights
  routes:
  - path: /
  run_command: gunicorn --worker-tmp-dir /dev/shm trydjango.wsgi