# Generated by Django 3.2.18 on 2023-03-31 18:14

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.ImageField(default='accounts/images/default.jpg', upload_to=accounts.models.recipe_image_upload_handler),
        ),
    ]
