# Generated by Django 3.2.18 on 2023-03-24 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_recipeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeimage',
            name='recipe',
            field=models.ForeignKey(default='recipes/images/default.jpg', on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
    ]
