# Generated by Django 3.2.18 on 2023-03-24 14:33

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20230324_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=models.ImageField(default='recipes/images/default.jpg', unique=True, upload_to=recipes.models.recipe_image_upload_handler),
        ),
    ]
